# Generated by Django 5.1.15 on 2026-10-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_must_change_password'),
        ('fleet', '0034_sector_vehicle_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sectors',
            field=models.ManyToManyField(blank=True, related_name='users', to='fleet.sector'),
        ),
    ]
