# Generated by Django 5.1.4 on 2026-09-21 16:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_remove_vehicle_current_driver_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vehicle',
            name='fleet_vehic_current_6d7ef3_idx',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='current_plate',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='reserved_plate',
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['status'], name='fleet_vehic_status__3e577d_idx'),
        ),
        migrations.AddConstraint(
            model_name='vehicleplate',
            constraint=models.UniqueConstraint(condition=models.Q(('ends_on__isnull', True)), fields=('vehicle', 'kind'), name='unique_active_plate_per_vehicle_and_kind'),
        ),
    ]
