# Generated by Django 5.1.4 on 2026-09-21 17:03

from django.db import migrations


def create_default_statuses(apps, schema_editor):
    VehicleStatus = apps.get_model('fleet', 'VehicleStatus')
    MaintenanceStatus = apps.get_model('fleet', 'MaintenanceStatus')
    
    vehicle_statuses = ["Ativo", "Indisponível", "Em manutenção", "Reserva"]
    maintenance_statuses = ["Aberta", "Concluída", "Cancelada"]
    
    for status_name in vehicle_statuses:
        VehicleStatus.objects.get_or_create(name=status_name, defaults={'active': True})
        
    for status_name in maintenance_statuses:
        MaintenanceStatus.objects.get_or_create(name=status_name, defaults={'active': True})

def remove_default_statuses(apps, schema_editor):
    # Opcional: Apenas passamos para não deletar status caso haja rollback, 
    # pois eles podem estar vinculados a dados reais.
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_remove_vehicle_fleet_vehic_current_6d7ef3_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_statuses, reverse_code=remove_default_statuses),
    ]
