# Generated by Django 5.1.4 on 2026-09-21 17:16

from django.db import migrations


def create_default_inspections(apps, schema_editor):
    VehicleInspectionType = apps.get_model('fleet', 'VehicleInspectionType')
    VehicleInspectionStatus = apps.get_model('fleet', 'VehicleInspectionStatus')
    
    types = ["Recebimento", "Devolução", "Rotina"]
    statuses = ["Aprovada", "Reprovada", "Aprovada com ressalvas"]
    
    for t in types:
        VehicleInspectionType.objects.get_or_create(name=t, defaults={'active': True})
        
    for s in statuses:
        VehicleInspectionStatus.objects.get_or_create(name=s, defaults={'active': True})

def remove_default_inspections(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_vehicleinspectionstatus_vehicleinspectiontype_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_inspections, reverse_code=remove_default_inspections),
    ]
