# Generated by Django 5.1.4 on 2026-09-21 17:20

from django.db import migrations


def create_default_fine_statuses(apps, schema_editor):
    VehicleFineStatus = apps.get_model('fleet', 'VehicleFineStatus')
    
    statuses = ["Pendente", "Em análise", "Recurso", "Paga", "Cancelada", "Encerrada"]
    
    for s in statuses:
        VehicleFineStatus.objects.get_or_create(name=s, defaults={'active': True})

def remove_default_fine_statuses(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0008_vehiclefinestatus_vehiclefine'),
    ]

    operations = [
        migrations.RunPython(create_default_fine_statuses, reverse_code=remove_default_fine_statuses),
    ]
