# Generated by Django 5.1.4 on 2026-09-21 17:31

from django.db import migrations
from django.conf import settings


def migrate_processes(apps, schema_editor):
    VehicleFine = apps.get_model('fleet', 'VehicleFine')
    Contract = apps.get_model('fleet', 'Contract')
    SEIProcess = apps.get_model('fleet', 'SEIProcess')
    SEIProcessStatus = apps.get_model('fleet', 'SEIProcessStatus')
    SEIProcessRelation = apps.get_model('fleet', 'SEIProcessRelation')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    
    statuses = ["Aberto", "Em andamento", "Encerrado", "Arquivado", "Cancelado"]
    
    for s in statuses:
        SEIProcessStatus.objects.get_or_create(name=s, defaults={'active': True})
        
    status_aberto = SEIProcessStatus.objects.get(name="Aberto")
    
    fine_ct = ContentType.objects.get_for_model(VehicleFine)
    for fine in VehicleFine.objects.exclude(process_number=""):
        process, _ = SEIProcess.objects.get_or_create(
            sei_number=fine.process_number,
            defaults={
                'title': f'Processo de Multa {fine.auto_number}',
                'status': status_aberto,
                'created_by': fine.created_by
            }
        )
        SEIProcessRelation.objects.get_or_create(
            process=process,
            content_type=fine_ct,
            object_id=fine.id,
            defaults={'created_by': fine.created_by}
        )

    contract_ct = ContentType.objects.get_for_model(Contract)
    User = apps.get_model(settings.AUTH_USER_MODEL)
    system_user, _ = User.objects.get_or_create(username="system", defaults={"is_active": False})
    
    for contract in Contract.objects.exclude(sei_number=""):
        process, _ = SEIProcess.objects.get_or_create(
            sei_number=contract.sei_number,
            defaults={
                'title': f'Processo do Contrato {contract.number}',
                'status': status_aberto,
                'created_by': system_user
            }
        )
        SEIProcessRelation.objects.get_or_create(
            process=process,
            content_type=contract_ct,
            object_id=contract.id,
            defaults={'created_by': system_user}
        )

def reverse_migrate_processes(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0010_seiprocessstatus_seiprocess_seiprocessrelation'),
    ]

    operations = [
        migrations.RunPython(migrate_processes, reverse_code=reverse_migrate_processes),
    ]
