# Generated by Django 5.1.4 on 2026-09-21 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0011_auto_20260921_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='sei_number',
        ),
        migrations.RemoveField(
            model_name='vehiclefine',
            name='process_number',
        ),
    ]
