# Generated by Django 5.1.4 on 2026-09-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0012_remove_contract_sei_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seiprocessrelation',
            name='object_id',
        ),
        migrations.AddField(
            model_name='seiprocessrelation',
            name='object_id',
            field=models.UUIDField(db_index=True),
        ),
    ]
