# Generated by Django 5.1.4 on 2026-09-21 18:35

from django.db import migrations


def seed_documents(apps, schema_editor):
    DocumentType = apps.get_model('fleet', 'DocumentType')
    DocumentStatus = apps.get_model('fleet', 'DocumentStatus')
    
    types = [
        "Contrato", "Termo", "SEI", "Multa", "Manutenção", 
        "Laudo", "Vistoria", "Documento do veículo", 
        "Documento administrativo", "Outros"
    ]
    for t in types:
        DocumentType.objects.get_or_create(name=t, defaults={"active": True})
        
    statuses = ["Ativo", "Arquivado"]
    for s in statuses:
        DocumentStatus.objects.get_or_create(name=s, defaults={"active": True})

def unseed_documents(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0014_documentstatus_documenttype_document_documentversion_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_documents, reverse_code=unseed_documents),
    ]
