# Generated by Django 5.1.4 on 2026-09-21 18:54

from django.db import migrations


def seed_parameters(apps, schema_editor):
    SystemParameter = apps.get_model('fleet', 'SystemParameter')
    
    SystemParameter.objects.get_or_create(
        key="CONTRACT_EXPIRY_WARNING_DAYS", 
        defaults={"value": "30", "description": "Dias de antecedência para alerta de vencimento de contrato"}
    )
    SystemParameter.objects.get_or_create(
        key="CONTRACT_EXPIRY_CRITICAL_DAYS", 
        defaults={"value": "15", "description": "Dias de antecedência para alerta crítico de vencimento de contrato"}
    )

def unseed_parameters(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0016_systemparameter'),
    ]

    operations = [
        migrations.RunPython(seed_parameters, reverse_code=unseed_parameters),
    ]
