# Generated by Django 5.1.4 on 2026-09-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0017_seed_system_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='cnh_category',
            field=models.CharField(blank=True, max_length=5, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='driver',
            name='cnh_expiration',
            field=models.DateField(blank=True, null=True, verbose_name='Validade CNH'),
        ),
        migrations.AddField(
            model_name='driver',
            name='cnh_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Nº CNH'),
        ),
    ]
