# Generated by Django 5.1.4 on 2026-09-23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


def copy_legacy_custody_info(apps, schema_editor):
    Vehicle = apps.get_model("fleet", "Vehicle")
    VehicleCustody = apps.get_model("fleet", "VehicleCustody")

    for vehicle in Vehicle.objects.exclude(custody_info="").exclude(custody_info__isnull=True).iterator():
        VehicleCustody.objects.create(
            vehicle=vehicle,
            kind="LEGADO",
            reference=vehicle.custody_info,
            starts_on=vehicle.created_at or django.utils.timezone.now(),
            created_by_id=vehicle.created_by_id,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0018_driver_cnh_category_driver_cnh_expiration_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleCustody",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("kind", models.CharField(choices=[("SEI", "SEI"), ("ACAUTELAMENTO", "Acautelamento"), ("OUTRO", "Outro"), ("LEGADO", "Registro legado")], default="OUTRO", max_length=20)),
                ("reference", models.CharField(max_length=120)),
                ("starts_on", models.DateTimeField(default=django.utils.timezone.now)),
                ("ends_on", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name="vehicle_custodies_created", to="accounts.user")),
                ("vehicle", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="custody_records", to="fleet.vehicle")),
            ],
            options={"ordering": ["-starts_on", "-created_at"]},
        ),
        migrations.RunPython(copy_legacy_custody_info, migrations.RunPython.noop),
    ]
