# Generated by Django 5.1.4 on 2026-09-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0020_seed_maintenance_type_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='sei_acautelamento',
            field=models.CharField(blank=True, max_length=100, verbose_name='SEI do acautelamento'),
        ),
    ]
