# Generated by Django 5.1.4 on 2026-09-23 14:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0021_driver_sei_acautelamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleCustody',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sei_number', models.CharField(max_length=100, verbose_name='SEI do acautelamento')),
                ('started_on', models.DateField(verbose_name='Início do acautelamento')),
                ('ended_on', models.DateField(blank=True, null=True, verbose_name='Fim do acautelamento')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custodies', to='fleet.vehicledriverassignment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
