# Generated by Django 5.1.4 on 2026-09-25 17:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0025_maintenance_workshop_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverCNHHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('renewal_date', models.DateField(verbose_name='Data da renovação')),
                ('new_expiration', models.DateField(verbose_name='Nova validade')),
                ('cnh_number', models.CharField(blank=True, max_length=20, verbose_name='Nº CNH')),
                ('cnh_category', models.CharField(blank=True, max_length=5, verbose_name='Categoria')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cnh_history', to='fleet.driver')),
            ],
            options={
                'ordering': ['-renewal_date', '-created_at'],
            },
        ),
    ]
