# Generated by Django 5.1.4 on 2026-09-29 18:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0026_driver_cnh_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='BDT',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('started_km', models.BigIntegerField(blank=True, null=True)),
                ('ended_km', models.BigIntegerField(blank=True, null=True)),
                ('total_km', models.BigIntegerField(blank=True, null=True)),
                ('management_id', models.CharField(blank=True, max_length=100)),
                ('management_name', models.CharField(blank=True, max_length=150)),
                ('source_updated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_synced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bdts', to='fleet.driver')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bdts', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-started_at', '-created_at'],
                'indexes': [models.Index(fields=['vehicle', '-started_at'], name='fleet_bdt_vehicle_ce9c4d_idx'), models.Index(fields=['driver', '-started_at'], name='fleet_bdt_driver__3d0e27_idx'), models.Index(fields=['management_id', '-started_at'], name='fleet_bdt_managem_063e62_idx')],
            },
        ),
    ]
