# Generated by Django 5.1.4 on 2026-09-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0027_bdt'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='horus_user_id',
            field=models.UUIDField(blank=True, help_text='ID do usuario na tabela users do Horus.', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='horus_fleet_id',
            field=models.UUIDField(blank=True, help_text='ID do veiculo na tabela fleets do Horus.', null=True, unique=True),
        ),
    ]
