# Generated by Django 5.1.4 on 2026-09-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0028_driver_horus_user_id_vehicle_horus_fleet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='ends_on',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='starts_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
