# Generated by Django 5.1.4 on 2026-09-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0029_alter_contract_ends_on_alter_contract_starts_on'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bdt',
            name='fleet_bdt_managem_063e62_idx',
        ),
        migrations.RemoveField(
            model_name='bdt',
            name='management_id',
        ),
        migrations.RemoveField(
            model_name='bdt',
            name='total_km',
        ),
        migrations.AddField(
            model_name='bdt',
            name='horus_active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bdt',
            name='horus_adm_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bdt',
            name='horus_management_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bdt',
            name='horus_sector_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bdt',
            name='horus_service_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bdt',
            name='latitude_match',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='bdt',
            name='latitude_retreat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='bdt',
            name='longitude_match',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='bdt',
            name='longitude_retreat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='bdt',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bdt',
            name='source_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bdt',
            name='ended_km',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bdt',
            name='external_id',
            field=models.UUIDField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bdt',
            name='started_km',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='bdt',
            index=models.Index(fields=['horus_management_id', '-started_at'], name='fleet_bdt_horus_m_46ca61_idx'),
        ),
        migrations.AddIndex(
            model_name='bdt',
            index=models.Index(fields=['source_updated_at'], name='fleet_bdt_source__a79ba9_idx'),
        ),
    ]
