# Generated by Django 5.1.4 on 2026-10-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0030_remove_bdt_fleet_bdt_managem_063e62_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bdt',
            name='departure_address',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='bdt',
            name='return_address',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
