# Generated by Django 5.1.15 on 2026-10-06 15:30

from django.db import migrations


def populate_sectors(apps, schema_editor):
    Sector = apps.get_model('fleet', 'Sector')
    Sector.objects.get_or_create(slug='adm', defaults={'name': 'ADM'})
    Sector.objects.get_or_create(slug='lei-seca', defaults={'name': 'LEI SECA'})

def reverse_populate(apps, schema_editor):
    Sector = apps.get_model('fleet', 'Sector')
    Sector.objects.filter(slug__in=['adm', 'lei-seca']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0034_sector_vehicle_sector'),
    ]

    operations = [
        migrations.RunPython(populate_sectors, reverse_populate),
    ]
