# Generated by Django 5.1.4 on 2026-10-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0043_crlv_licensing_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='chassi',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vehiclecrlv',
            name='chassi',
            field=models.CharField(blank=True, max_length=17),
        ),
    ]
